### PR TITLE
JCLOUDS-935. Move AttachDisk.InitializeParams to URI for diskType

### PR DESCRIPTION
**Pull request by abayer**
Note that two tests are failing right now with or without this.

### CODE REVIEW

**Comment by nacx** [comment]
The change lgtm. Which tests are failing? I was able to run the live tests without issues in the current master.

**Comment by jclouds-mirror** [comment]
I think it may just be something in my local environment - ignore me! =)

**Comment by abayer** [comment]
The failing tests - https://gist.github.com/abayer/72554e8861873b3f4750 - sometimes they seem to pass, sometimes they don't, and I can't figure out why.

**Comment by abayer** [comment]
Well that was dumb. I forgot what repo I was in and merged it. Oops. Will push by hand.

**Pull request merged**
