### PR TITLE
Support newly-introduced nearline storage

### PR DESCRIPTION
**Pull request by snotling**

### CODE REVIEW

**Comment by andrewgaul** [comment]
Related issue: [JCLOUDS-848](https://issues.apache.org/jira/browse/JCLOUDS-848)

@snotling Can you add some kind of live test to exercise this functionality, e.g., create object with this storage class then check if it has the correct class?

@danbroudy Anything else we need to do for this?

**Comment by snotling** [comment]
@andrewgaul I hadn't checked if there was already a JIRA issue for this :)

Anyway, I switched from *DRA* to *nearline* in ``BucketApiLiveTest.testCreateBucket()`` -- don't know if you wanted something more convoluted...
I had to change the location to *US*, as regional locations are only supported for *DRA*.
Speaking of *DRA*, it is already tested in ``BucketApiLiveTest.testCreateBucketWithOptions()``.
*Standard* buckets are not tested anywhere though as far as I know.

**Comment by snotling** [comment]
Hum, when I think of it, that's a pretty lame idea to use *nearline* in the "main" ``testCreateBucket()`` method, given the fact that all the object API tests rely on it...

@andrewgaul How did see the modification to add tests for *nearline* buckets? In fact, in addition to the storage class, there's also the bucket location that could be interesting to test.
Maybe tests method should be "parameterized" in order to check all(?) the possible combinations.

**Comment by andrewgaul** [comment]
@snotling rackspace-cloudfiles-us runs all the tests against every storage class and region which takes too long and we plan to only run these tests against one region in the future.  However it would be good to parameterize just one test to loop over all these combinations to check the expected and actual bucket attributes.

**Comment by andrewgaul** [comment]
I added the needed tests and pushed to master as 2455f9445b3fbdfe20006e359945762639a76a66 and 4e8858a472104c6904f35e94fa5889906582813e and to 1.9.x as ef6dd087da3193c3ac472a6457de1459c47bbd13 and 3d39bd3262d3ec4ae83bcf47af4d45ddff7bb3e1.  Thank you for your contribution @snotling!

**Pull request closed without merging**
