### PR TITLE
FIx issue with blob name / encoding for getBlob method

### PR DESCRIPTION
**Pull request by freddy33**
The getBlob did not encode the /

### CODE REVIEW

**Comment by andrewgaul** [comment]
@timuralp Can you look at this?

**Comment by timuralp** [comment]
Yep, will look into this. Possibly related to the changes in core.

**Comment by timuralp** [comment]
@freddy33 looking into the Google provider, it's not clear to me that "/" should actually be encoded. Putting an object, such as _foo/bar_ results in _foo/bar_ being placed in the object store (and I observe that this is the object returned when listing the store contents). I see an issue with ```getBlob()```, however. Without any changes, ```getBlob(<container>, "foo/bar")``` fails to retrieve the blob _foo/bar_ and returns ```null``` instead -- clearly wrong.

**Comment by timuralp** [comment]
Ok, the commit makes more sense to me now with respect to what was changed and why. There is a bit of an inconsistency with the google provider here in two aspects: not using ```Strings2.urlEncode()``` and not encoding parameters of the requests in the HTTP layer -- I'd like to figure out why the HTTP transport doesn't encode the parameters correctly (like S3 does, for example). Will look into this particular bit tomorrow.

**Comment by freddy33** [comment]
Thanks for looking into it.
BTW: I did not see if the ACL commands needs path encoding or not?

**Comment by timuralp** [comment]
@freddy33 I believe the same problem exists in the ACL controls. The file to look at is ```ObjectAccessControlsApi.java```. Anytime a path parameter may include "/", we would need to escape it. This is an issue for all requests in that API.

I'm going to fix this problem on master (and the upcoming jclouds 2.0 release) by extending the jclouds annotation processor to consider and honor an ```@Encoded``` annotation that may be attached to any request. I will then go through and annotate all of the Google Storage requests appropriately.

Filed a JIRA issue here: https://issues.apache.org/jira/browse/JCLOUDS-1008

As for the 1.9 fix-up, it looks fine to me, aside from not using ```Strings2.encode()``` -- could you change the PR to do that? Fixing up the ACL calls would also be preferred.

**Comment by freddy33** [comment]
Done.
I still encode only names that contains / before calling `Strings2.urlEncode()` .
Which means that characters that are not / (space *) but have URL encoding will be encoded only if the filename has a /.
Kind of strange behavior I guess, no?

**Comment by timuralp** [comment]
@freddy33 yes, it is strange, but I believe it's ok. For context: in 1.9, jclouds annotation processor will encode the entirety of the path. There are some caveats with how it works and known issues (see https://issues.apache.org/jira/browse/JCLOUDS-217 and associated commits for more details), but that's the gist.

The annotation processor, however, will not encode any "/" characters in the path, so a request for "http://host/b/bucket/o/foo/bar" is not translated to "http://host/b/bucket/o/foo%2Fbar". The prior behavior was to fix this up in the google provider, but clearly not complete for all places where it is called.

:+1:

**Comment by andrewgaul** [comment]
Let's address this issue in master before discussing backporting to 1.9.x.  Note that we do not plan further 1.9 releases.

**Comment by timuralp** [comment]
Sounds good. Opened PR for jclouds core changes and google-cloud-storage: https://github.com/jclouds/jclouds/pull/861 and https://github.com/jclouds/jclouds-labs-google/pull/167

**Comment by Domaxamas** [comment]
Its jason from Glenwood springs! Thanks

**Comment by andrewgaul** [comment]
@freddy33 Is this still an issue in master?

**Comment by freddy33** [comment]
No, issue fixed!

**Pull request closed without merging**
