### PR TITLE
Updated BackendServiceOptions to AutoValue + Builder

### PR DESCRIPTION
**Pull request by danbroudy**
Converts another Options class to AutoValue + Builder 

For consistency I think all Options classes should be converted to AutoValue + Builder.
Sound good? Should I continue down this path?

### CODE REVIEW

**Comment by nacx** [comment]
Auto has many benefits for the regular pojos (and that's why we want to use it), so I'd say go ahead!

**Comment by nacx** [comment]
@danbroudy the PR lgtm. Are you planning to add more code or can I just merge it?

**Comment by danbroudy** [comment]
I am planning to add more code. I apologize for the the delay.

**Comment by danbroudy** [comment]
Happy to squash. I figured it may be easier to review in individual commits.

**Comment by nacx** [comment]
No need to squash. Thanks for splitting the chanes in several commits it was indeed easier to review.
Merged to master!

**Pull request closed without merging**
