### PR TITLE
Updates to InstanceApi. 100% coverage

### PR DESCRIPTION
**Pull request by danbroudy**
InstanceApi is still lacking some LiveTest Coverage.

### CODE REVIEW

**Comment by pedro-ribeiro** [comment]
@danbroudy, if I'm looking at this right, a serviceAccounts field was added to NewInstance, but no further wiring was done and the library does not provide a way to set this value on node creation. Was this on purpose or just lack of time?

Thanks!

**Comment by danbroudy** [comment]
You are correct. This should change. I think NewInstance needs a Builder pattern so that you can customize new instances more than the two creation options there are now.

**Comment by nacx** [comment]
@pedro-ribeiro Do you mean that there should be a way in the ComputeService to propagate the service accounts [here](https://github.com/jclouds/jclouds-labs-google/blob/master/google-compute-engine/src/main/java/org/jclouds/googlecomputeengine/compute/GoogleComputeEngineServiceAdapter.java#L165)?

I'm not the GCE expert, but this is something that could be easily added to the GCETemplateOptions and considered there. If that is the case, mind opening a JIRA improvement for this? And even better would you like to try contributing that patch? :)

**Comment by pedro-ribeiro** [comment]
This follow up issue has been created: https://issues.apache.org/jira/browse/JCLOUDS-906

Unfortunately, even though this would make my life much easier, I probably won't have the time to contribute a patch. :/

**Comment by danbroudy** [comment]
#142

**Pull request closed without merging**
