### PR TITLE
JCLOUDS-683: Use OAuth from the main repo

### PR DESCRIPTION
**Pull request by nacx**
https://issues.apache.org/jira/browse/JCLOUDS-683

### CODE REVIEW

**Comment by nacx** [comment]
Note that this PR will fail the build until the snapshots from the recently merged PR in the main repo are published to the ASP snapshot repository.

**Comment by nacx** [comment]
rebuild please

**Comment by danbroudy** [comment]
Did you run live tests?

**Comment by danbroudy** [comment]
Just one live test should be enough to show its working. Thanks for doing this!

**Comment by nacx** [comment]
I can confirm it is working then :) I plan to spend some time this week working on the GCE provider. Let's see if we can get it promoted too! Thanks for the feedback!

**Pull request merged**
