### PR TITLE
JCLOUDS-944: Promote Google Cloud Storage to core

### PR DESCRIPTION
**Pull request by gaul**

### CODE REVIEW

**Comment by andrewgaul** [comment]
@nacx Please review modified `README.md`.  Do we need to do anything else to retire this repository, e.g., modify build scripts?

**Review by nacx — APPROVED** [review]

**Comment by nacx** [comment]
Yes, we need to remove the jclouds-labs-google repo from the script here:
https://dist.apache.org/repos/dist/dev/jclouds/ 

And we need to disable the jclouds-labs-google build for the master and 2.0.x branch in Jenkins.

This said, IMO it would make sense to promote the providers in 2.0.x too. I mean, we say we don't need to keep backwards compatibility in labs providers, but in this case, upgrading would be just a change of the groupId; not a big deal. And we could release a new 2.0.2 after promoting? There are many Azure ARM improvements, so a release would make sense. Thoughts about this, @andrewgaul  @demobox @andreaturli ?

**Comment by andrewgaul** [comment]
I dislike promoting a provider in a bugfix release but if others prefer this I will do the work.  It would be great to release a new version although I prefer 2.1.0.

**Comment by nacx** [comment]
Let's promote it only in master then.

Should we then create a copy of the release scripts for 2.0.x, so we can cleanly release with or without the jclouds-labs-google repo? Just to make we don't get into issues in the middle of a release process (which is kind of a PITA :D).

**Comment by nacx** [comment]
BTW, in order to release 2.1.0 we must first fix [JCLOUDS-1275 ](https://issues.apache.org/jira/browse/JCLOUDS-1275).

**Pull request merged**
