### PR TITLE
add rewrite to ObjectApi

### PR DESCRIPTION
**Pull request by danbroudy**

### CODE REVIEW

**Comment by andrewgaul** [comment]
@danbroudy Can you fix the Checkstyle violations?

**Comment by danbroudy** [comment]
My mistake, I guess thats what I get for removing newlines after doing checkstyle.

**Comment by andrewgaul** [comment]
Corrected test name and pushed to master as 413b03b6bf05a647c135ac8d808fd0bd6438375f and 1.9.x as 72db4f53366ff466ab6714a8def8359f6c40f6de.

**Comment by danbroudy** [comment]
Thanks!

**Pull request closed without merging**
